// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJ60HzvaPo3314HpLvJYkcp4Z4zEKElI',
    appId: '1:992209225498:web:15e78cf0123c548ae1cea3',
    messagingSenderId: '992209225498',
    projectId: 'login-c8261',
    authDomain: 'login-c8261.firebaseapp.com',
    storageBucket: 'login-c8261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCN5M0zvPL1_ZKQ3X-h7HAVlKi_malt8',
    appId: '1:992209225498:android:d00440dbce306f4ee1cea3',
    messagingSenderId: '992209225498',
    projectId: 'login-c8261',
    storageBucket: 'login-c8261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjegiE_-mCLqXJlo9Xw7HaU2_kyP6Dv5w',
    appId: '1:992209225498:ios:1a78a3252ce51388e1cea3',
    messagingSenderId: '992209225498',
    projectId: 'login-c8261',
    storageBucket: 'login-c8261.appspot.com',
    iosBundleId: 'com.qq.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjegiE_-mCLqXJlo9Xw7HaU2_kyP6Dv5w',
    appId: '1:992209225498:ios:1a78a3252ce51388e1cea3',
    messagingSenderId: '992209225498',
    projectId: 'login-c8261',
    storageBucket: 'login-c8261.appspot.com',
    iosBundleId: 'com.qq.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxJ60HzvaPo3314HpLvJYkcp4Z4zEKElI',
    appId: '1:992209225498:web:6cce93a680be89ffe1cea3',
    messagingSenderId: '992209225498',
    projectId: 'login-c8261',
    authDomain: 'login-c8261.firebaseapp.com',
    storageBucket: 'login-c8261.appspot.com',
  );
}
